{"version":1,"defects":{"Tests\\Unit\\RouterTest::test_it_register_a_get_route":4,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception":4,"Tests\\Unit\\RouterTest::test_it_register_a_route":4,"Tests\\Unit\\RouterTest::test_it_register_a_post_route":4,"Tests\\Unit\\RouterTest::test_there_are_no_routes_when_router_is_empty":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":4,"Warning":6,"Tests\\Unit\\ContainerTest::test_it_resolves_a_class_with_dependencies_from_the_container":4},"times":{"Tests\\Unit\\RouterTest::it_register_a_route":0.001,"Tests\\Unit\\RouterTest::test_it_register_a_route":0,"Tests\\Unit\\RouterTest::test_it_register_a_get_route":0,"Tests\\Unit\\RouterTest::test_it_register_a_post_route":0,"Tests\\Unit\\RouterTest::test_there_are_no_routes_when_router_is_empty":0,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0,"Tests\\Unit\\ContainerTest::test_it_resolves_a_class_from_the_container":0.002,"Warning":0.001,"Tests\\Unit\\ContainerTest::test_it_resolves_a_class_with_dependencies_from_the_container":0}}